version: "3"
volumes:
  app:
    driver: local
services:
  app:
    image: snaba/front:dev
    build:
      context: .
    ports:
      - "13443:13443"
      - "13501:13501"
    volumes:
      - "app:/app"
